# -- Master pipline for WPP Cloud Studio

trigger: none
pr: none

name: WPP Cloud Studio  - ${{ parameters.Environment }}

#-- Parameters
parameters:
- name: Environment
  type: string
  values:
  - perf

- name: TerraformVersion
  type: string
  default: '1.0.2'

- name: TerraformStorageProvision
  type: boolean
  default: false
  values:
  - true
  - false

#-- Varibales
variables:
- template: ./Environment_${{ parameters.Environment }}.yml
- group: wppstorageautomationGroup-${{ parameters.Environment }}
- group: Cloud Studio Keyvault - ${{ parameters.Environment }}

stages:
- template: ./terraform-stages-template-perf.yml
  parameters:
    Environment: ${{ parameters.Environment }}
    TerraformDirectory: ${{ variables.TerraformMasterModuleDirectoryName }}
    TerraformVersion: ${{ parameters.TerraformVersion }}
    provisionStorage: ${{ parameters.TerraformStorageProvision }}
    location: ${{ variables.location }}
    locationshortprefix: ${{ variables.locationshortprefix }}